### ISSUE TITLE
mongo setup

### ISSUE THREAD

**Issue by misi** [IdentityPython/pyop#27]
@c00kiemon5ter 
I have a SATOSA/Pyop setup with mongo db, but I am not sure how data expiry and aging works in such setup.

Where can I find any info about this and mongo setup? 

How data expiry/aging works in such pyop mongo setup?
e.g. token expire very fast and after it I guess we can delete them after some wait.

I found there is a expire-data function in mongo
https://docs.mongodb.com/manual/tutorial/expire-data/

Can you please help me?
Any info would be highly appreciated!

**Comment by johanlundberg** [comment]
As far as I know the only thing pyop does for helping with data expiry is to set modified_ts when saving a mongodb document. Had the expire data feature existed and I had known about when I added modified_ts to the mongo docs in pyop I had choosen a datetime instead of time. Sadly this is not the case now.

Without changing the current code (PRs welcome :)) I think the easiest way to expire data is set up a cronjob that (perhaps daily) checks the different documents modiefied_ts and removes those you deem old.

**Comment by misi** [comment]
@johanlundberg  
Many many thanks for your fast help and reply!  

For me the suggested daily cron is perfect. 
Now I see how it works.

Appreciated your help!
